language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester@v5.0.0
- bower install
script: xvfb-run npm run test-lint
cache:
  directories:
    - node_modules
